trigger:
- main

pool:
  name: $(pool)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    if [ "$(uname)" == "Linux" ]; then
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
    else
      echo "Docker installation skipped on non-Linux agent."
    fi
  displayName: 'Install Docker'

- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'artifactory'
    cliInstallationRepo: jfrog-cli

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/build-compose.yml'
    qualifyImageNames: false
    action: 'Build services'

- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'artifactory'
    targetRepo: 'docker-virtual'
    imageName: 'https://docker.io/library/swarmops-proxy'