trigger:
  none

pool:
  name: $(pool)
  demands: 
  - Agent.Name -equals $(agent-name)
 
variables:
  tag: $(Build.BuildNumber)
  imageNamePrefix: 'swarmops'
  buildAndPush: true

stages:

  - stage: BuildAndPush
    condition: eq(variables['buildAndPush'], true)
    jobs:
      - job: BuildAndPush
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |

              # docker system prune -af
              
              # Stop older image services
              docker ps | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-
              PREV_IMAGE_TAG=$(docker ps | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops- | sed -n 's/.*:\([0-9]*\.[0-9]*\) .*/\1/p' | head -n 1)
              IMAGE_TAG=$PREV_IMAGE_TAG docker compose -f build-compose.yml down 
              docker ps | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-

              # Remove older images
              docker images | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-
              docker rmi -f $(docker images | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-)
              docker images | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-

              # build Proxy
              cd $(Build.SourcesDirectory)/proxy
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag) -f $(Build.SourcesDirectory)/proxy/Dockerfile .

              # build Frontend
              cd $(Build.SourcesDirectory)/frontend
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag) -f $(Build.SourcesDirectory)/frontend/Dockerfile .

              # build Backend
              cd $(Build.SourcesDirectory)/backend
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag) -f $(Build.SourcesDirectory)/backend/Dockerfile .
              docker images | grep $(tag)
              # echo "Build and Push Job 1 ran"
   
        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'


        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'

        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'
  
  - stage: ComposeUp
    dependsOn: BuildAndPush
    condition: succeeded('BuildAndPush')  
    jobs:
      - job: ComposeUp
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              
              IMAGE_TAG=$(tag) docker compose -f build-compose.yml up -d
              
              echo "Compose Up Task ran"

  
  - stage: ComposeDown
    condition: eq(variables['buildAndPush'], false)
    jobs:
      - job: ComposeDown
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: | 

              # Stop older image services
              docker ps | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-
              PREV_IMAGE_TAG=$(docker ps | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops- | sed -n 's/.*:\([0-9]*\.[0-9]*\) .*/\1/p' | head -n 1)
              IMAGE_TAG=$PREV_IMAGE_TAG docker compose -f build-compose.yml down 
              docker ps | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-

              # Remove older images
              docker images | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-
              docker rmi -f $(docker images | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-)
              docker images | grep artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-

              echo "Compose Down Task ran"

      
 