trigger:
 branches:
   include:
   - deploy-services
 
pool:
  name: $(pool)
  demands: 
  - Agent.Name -equals $(agent-name)
 
variables:
  tag: $(Build.BuildNumber)
  imageNamePrefix: 'swarmops'
 
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker system prune -af

      # build Proxy
      docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag) -f $(Build.SourcesDirectory)/proxy/Dockerfile .

      # build Frontend
      docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag) -f $(Build.SourcesDirectory)/frontend/Dockerfile .

      # build Backend
      docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag) -f $(Build.SourcesDirectory)/backend/Dockerfile .
      docker images | grep $(tag)
      
 
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'artifactory'
    targetRepo: 'rp-docker-local'
    imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'


- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'artifactory'
    targetRepo: 'rp-docker-local'
    imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'artifactory'
    targetRepo: 'rp-docker-local'
    imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'