trigger:
  none

pool:
  name: $(pool)
  demands: 
  - Agent.Name -equals $(agent-name)
 
variables:
  tag: $(Build.BuildNumber)
  imageNamePrefix: 'swarmops'
  buildAndPush: false

stages:
  - stage: dockerps
    jobs:
      - job: dockerps
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: | 
                # docker rmi -f swarmops_frontend swarmops_backend swarmops_proxy
                docker images
                docker rmi -f $(docker images | grep swarmops)
                docker ps 
                # docker stop 4f1c 19d4 e86b
                # docker ps 
                # docker rmi -f f08e39122805 1891224f54e3 7de16dd97504
                docker images

                echo "LATEST_IMAGE_TAG=$(Build.BuildNumber)" > $(Build.SourcesDirectory)/sample.txt
                echo "LATEST_IMAGE_TAG=$(Build.BuildNumber)" > $(Build.SourcesDirectory)/.env
          # - task: InlinePowershell@1
          #   inputs:
          #     Script: 'Set-Content $(Build.SourcesDirectory)/.env "LATEST_IMAGE_TAG=$(Build.BuildNumber)"'

  - stage: BuildAndPush
    condition: eq(variables['buildAndPush'], true)
    jobs:
      - job: BuildAndPush
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |

              # docker system prune -af

              # build Proxy
              cd $(Build.SourcesDirectory)/proxy
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag) -f $(Build.SourcesDirectory)/proxy/Dockerfile .

              # build Frontend
              cd $(Build.SourcesDirectory)/frontend
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag) -f $(Build.SourcesDirectory)/frontend/Dockerfile .

              # build Backend
              cd $(Build.SourcesDirectory)/backend
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag) -f $(Build.SourcesDirectory)/backend/Dockerfile .
              docker images | grep $(tag)
              # echo "Build and Push Job 1 ran"
   
        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'


        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'

        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'
  
  - stage: ComposeUp
    dependsOn: BuildAndPush
    condition: succeeded('BuildAndPush')  
    jobs:
      - job: ComposeUp
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # export IMAGE_TAG=
              docker compose -f build-compose.yml up
              echo "Compose Up Task ran"

  
  - stage: ComposeDown
    condition: eq(variables['buildAndPush'], false)
    jobs:
      - job: ComposeDown
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker ps
              
              docker compose -f build-compose.yml down
              
              docker ps

              echo "Compose Down Task ran"

      
 