# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: $(pool)
  demands:
  - Agent.Name -equals $(agent-name)

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker images'
# - task: DockerCompose@0
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerComposeFile: '**/build-compose.yml'
#     action: 'Run services'
#     buildImages: false
