trigger:
  none

pool:
  name: $(pool)
  demands: 
  - Agent.Name -equals $(agent-name)
 
variables:
  tag: $(Build.BuildNumber)
  imageNamePrefix: 'swarmops'
  buildAndPush: false

stages:

  - stage: BuildAndPush
    condition: eq(variables['buildAndPush'], true)
    jobs:
      - job: BuildAndPush
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |

              # docker system prune -af

              docker images
              docker rmi -f $(docker images | grep swarmops)
              docker ps 
              docker images

              LATEST_IMAGE_TAG=$(Build.BuildNumber)
              export LATEST_IMAGE_TAG
              echo "$LATEST_IMAGE_TAG"

              # build Proxy
              cd $(Build.SourcesDirectory)/proxy
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag) -f $(Build.SourcesDirectory)/proxy/Dockerfile .

              # build Frontend
              cd $(Build.SourcesDirectory)/frontend
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag) -f $(Build.SourcesDirectory)/frontend/Dockerfile .

              # build Backend
              cd $(Build.SourcesDirectory)/backend
              docker build -t artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag) -f $(Build.SourcesDirectory)/backend/Dockerfile .
              docker images | grep $(tag)
              # echo "Build and Push Job 1 ran"
   
        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-proxy:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'


        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-frontend:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'

        - task: ArtifactoryDocker@1
          inputs:
            command: 'push'
            artifactoryService: 'artifactory'
            targetRepo: 'rp-docker-local'
            imageName: 'artifacts.realpage.com/rp-docker-local/dvo/swarm/$(imageNamePrefix)-backend:$(tag)'
            collectBuildInfo: true
            buildName: '$(Build.DefinitionName)'
            buildNumber: '$(Build.BuildNumber)'
  
  - stage: ComposeUp
    dependsOn: BuildAndPush
    condition: succeeded('BuildAndPush')  
    jobs:
      - job: ComposeUp
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              
              docker compose -f build-compose.yml up -d
              
              git config --global user.email "abhishek.ganji@realpage.com"
              git config --global user.name "Abhishek Ganji"
              git add .env
              git commit -m "Updated build ID in .env"
              git push origin HEAD:refs/heads/deploy-services
              
              echo "Compose Up Task ran"

  
  - stage: ComposeDown
    condition: eq(variables['buildAndPush'], false)
    jobs:
      - job: ComposeDown
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker ps
              
              docker ps -a
              
              cat .env
              
              docker compose -f build-compose.yml down
              
              docker ps

              echo "Compose Down Task ran"

      
 