trigger:
- main

pool:
  name: $(pool)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install -y docker-ce docker-ce-cli containerd.io
    sudo systemctl start docker
    sudo systemctl enable docker
  displayName: 'Install Docker on Rocky Linux'

- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'artifactory'
    cliInstallationRepo: jfrog-cli

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/build-compose.yml'
    qualifyImageNames: false
    action: 'Build services'

- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'artifactory'
    targetRepo: 'docker-virtual'
    imageName: 'https://docker.io/library/swarmops-proxy'