# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: $(pool)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'artifactory'
    cliInstallationRepo: 'jfrog-cli-v2'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/build-compose.yml'
    qualifyImageNames: false
    action: 'Build services'
    
# - task: ArtifactoryDocker@1
#   inputs:
#     command: 'push'
#     artifactoryService: 'artifactory'
#     targetRepo: 'rp-docker-local'
#     imageName: 'swarmops_*'
#     collectBuildInfo: true
#     buildName: '$(Build.DefinitionName)'
#     buildNumber: '$(Build.BuildNumber)'