
services:
  frontend:
    
    image: artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-frontend:$IMAGE_TAG
    container_name: swarmops_frontend    

    ports:
      - '8001:80'  # Exposes the frontend on port 8001
    volumes:
      - ./frontend:/app  # Mounts the local frontend directory to /app in the container for live updates


  backend:
  
    image: artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-backend:$IMAGE_TAG
    container_name: swarmops_backend    

    ports:
      - '8002:5000'  # Exposes the backend on port 8002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows the backend to access Docker socket
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  
  
  proxy:
  
    image: artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-proxy:$IMAGE_TAG
    container_name: swarmops_proxy    

    ports: ['8090:80']
    depends_on:
      - frontend
      - backend
    
  db:
    image: mongo:latest    
    ports:      
      - "27017:27017"    
    container_name: swarmops_db    
    stop_signal: SIGTERM    
    volumes:       
      - database:/data/db  

volumes:  
  database: 