
services:
  frontend:
    
    image: artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-frontend:20250122.5
    ports:
      - '8001:80'  # Exposes the frontend on port 8001
    depends_on:
      - backend  # Ensures that the backend service starts before the frontend
    volumes:
      - ./frontend:/app  # Mounts the local frontend directory to /app in the container for live updates


  backend:
  
    image: artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-backend:20250122.5
    ports:
      - '8002:5000'  # Exposes the backend on port 8002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows the backend to access Docker socket
    depends_on:
      - proxy
      - db
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  
  
  proxy:
  
    image: artifacts.realpage.com/rp-docker-local/dvo/swarm/swarmops-proxy:20250122.5
    ports: ['8090:80']
    
  db:
    image: mongo:latest    
    ports:      
      - "27017:27017"    
    container_name: db    
    stop_signal: SIGTERM    
    volumes:       
      - database:/data/db  
    depends_on:
      - proxy

volumes:  
  database: 