
services:
  frontend:
    build: 
      context: ./frontend 
    ports:
      - '8001:80'  
    depends_on:
      - backend  
    volumes:
      - ./frontend:/app  


  backend:
    build:
      context: ./backend 
    ports:
      - '8002:5000' 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    depends_on:
      - proxy
      - db
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  
  
  proxy:
    build: ./proxy
    ports: ['8090:80']
    
  db:
    image: mongo:latest    
    ports:      
      - "27017:27017"     
    stop_signal: SIGTERM    
    volumes:       
      - database:/data/db  
    depends_on:
      - proxy

volumes:  
  database: 
