version: '3.8'  # Use the latest version for better features

services:
  frontend:
    build: 
      context: ./frontend  # Specify the build context
    ports:
      - '8001:80'  # Exposes the frontend on port 8001
    depends_on:
      - backend  # Ensures that the backend service starts before the frontend
    volumes:
      - ./frontend:/app  # Mounts the local frontend directory to /app in the container for live updates

  backend:
    build:
      context: ./backend  # Specify the build context
    ports:
      - '8002:5000'  # Exposes the backend on port 8002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows the backend to access Docker socket
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  proxy:
    build: ./proxy
    ports: ['8090:80']
