
services:
  frontend:
    container_name: swarmops_frontend   
    build: 
      context: ./frontend  # Specify the build context
    ports:
      - '8001:80'  # Exposes the frontend on port 8001
    depends_on:
      - backend  # Ensures that the backend service starts before the frontend
    volumes:
      - ./frontend:/app  # Mounts the local frontend directory to /app in the container for live updates
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /app


  backend:
    container_name: swarmops_backend  
    build:
      context: ./backend  # Specify the build context
    ports:
      - '8002:5000'  # Exposes the backend on port 8002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows the backend to access Docker socket
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  
  
  proxy:
    container_name: swarmops_proxy    
    build: ./proxy
    ports: ['8090:80']
    develop:
      watch: 
        - action: sync+restart
          path: ./proxy/default.conf
          target: /etc/nginx/conf.d

  db:
    container_name: swarmops_db    
    image: mongo:latest    
    ports:      
      - "27017:27017"    
    stop_signal: SIGTERM    
    volumes:       
      - database:/data/db  
volumes:  
  database: 
