services:
  frontend:
    build: ./frontend
    ports: ['8001:80']
  backend:
    build: ./backend
    ports: ['8002:5000']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  proxy:
    build: ./proxy
    ports: ['8090:80']
